import type { RegistrationCopy } from "@/types/inscricao";

const cargoOptions = [
  "Bispo",
  "Padre",
  "Diácono",
  "Religioso(a)",
  "Seminarista",
  "Leigo(a)",
  "Professor(a)",
  "Pesquisador(a)",
  "Estudante",
  "Outro"
];

const areaAtuacaoOptions = [
  "Teologia Sistemática",
  "Teologia Bíblica",
  "Teologia Moral",
  "Espiritualidade",
  "Liturgia",
  "Catequese",
  "Pastoral",
  "Direito Canônico",
  "Filosofia",
  "Ciências da Religião"
];

const modalidadeParticipacaoOptions = [
  "Participante",
  "Participante com certificado",
  "Apresentação de Comunicação Científica",
  "Conferencista convidado"
];

const specialNeedsOptions = [
  "Acessibilidade física",
  "Intérprete de Libras",
  "Tradução simultânea",
  "Alimentação especial",
  "Outro"
];

const preferredLanguageOptions = ["Português", "Espanhol", "Inglês", "Italiano", "Francês"];

const sexoOptions = ["Masculino", "Feminino"];
const estadoCivilOptions = ["Solteiro(a)", "Casado(a)", "Religioso(a)", "Sacerdote", "Bispo", "Outro"];

export const registrationContent: Record<"pt" | "en" | "it", RegistrationCopy> = {
  pt: {
    languageLabels: { en: "Inglês", pt: "Português", it: "Italiano" },
    required: "Obrigatório",
    submitting: "Enviando...",
    submit: "Continuar para o pagamento",
    remove: "Remover",
    fileButton: "Anexar arquivo PDF",
    hero: [
      "I Congresso internacional de teologia",
      "Sobre a Paternidade de Deus",
      "Entre Dogma e Devoção",
      "Recebestes um Espírito de filhos adotivos, pelo qual clamamos: Abbá, Pai!",
      "(Gl 4,6)"
    ],
    fields: {
      personal: "1. Dados pessoais",
      fullName: "Nome Completo:",
      badgeName: "Nome para credencial:",
      birthDate: "Data de nascimento:",
      cpf: "CPF:",
      passport: "Passaporte (estrangeiros):",
      nationality: "Nacionalidade:",
      gender: "Sexo:",
      marital: "Estado Civil:",
      contact: "2. Contatos",
      phone: "Telefone/WhatsApp:",
      email: "E-mail:",
      address: "Endereço:",
      city: "Cidade:",
      state: "Estado:",
      country: "País:",
      postal: "CEP:",
      affiliation: "3. Vínculo eclesial / acadêmico",
      role: "Cargo/Função:",
      field: "Área de atuação:",
      other: "Outra Qual?",
      participation: "4. Modalidade de participação",
      academic: "5. Inscrição de trabalhos acadêmicos",
      paperQuestion: "Vai Apresentar trabalhos acadêmicos?",
      paperTitle: "Título do trabalho:",
      thematicArea: "Área temática:",
      needs: "6. Necessidades especiais",
      hasNeeds: "Possui alguma necessidade específica?",
      which: "Qual?",
      requires: "Necessita de:",
      lodging: "7. Hospedagem e Logística",
      lodgingQuestion: "Necessita de informações sobre hospedagem?",
      arrival: "Data prevista de chegada:",
      departure: "Data prevista de saída:",
      cultural: "Participará dos eventos culturais e visitas guiadas?",
      language: "8. Idioma preferencial",
      certification: "9. Certificação",
      wantsCertificate: "Deseja certificado?",
      certificateName: "Nome exatamente como deverá constar no certificado:",
      image: "10. Autorização de uso de imagem",
      imageText:
        "Autorizo a utilização de minha imagem, voz e participação em fotografias, gravações e transmissões realizadas durante o I Congresso Internacional de Teologia sobre a Paternidade de Deus, para fins institucionais, acadêmicos, evangelizadores e promocionais, sem ônus para a organização.",
      commitment: "11. Termo de compromisso",
      commitmentText:
        "Declaro que as informações prestadas são verdadeiras e que estou ciente das normas de participação do Congresso.",
      commitmentCity: "Cidade:",
      commitmentDate: "Data:",
      signature: "Assinatura:",
      termsAcceptancePrefix: "Li e aceito os",
      termsAcceptanceLink: "Termos de Uso",
      termsAcceptanceSuffix: " para continuar a inscrição.",
      termsAcceptanceError: "Aceite os Termos de Uso para continuar."
    },
    yesNo: ["Sim", "Não"],
    sexoOptions,
    estadoCivilOptions,
    cargoOptions,
    areaAtuacaoOptions,
    modalidadeParticipacaoOptions,
    specialNeedsOptions,
    preferredLanguageOptions
  },
  en: {
    languageLabels: { en: "English", pt: "Portuguese", it: "Italian" },
    required: "Required",
    submitting: "Sending...",
    submit: "Register",
    remove: "Remove",
    fileButton: "Attach PDF file",
    hero: [
      "1st International Congress on Theology",
      "On the Fatherhood of God",
      "Between Dogma and Devotion",
      "You received a Spirit of adoption, through whom we cry out: Abba, Father!",
      "(Gal 4:6)"
    ],
    fields: {
      personal: "1. Personal Details",
      fullName: "Full Name:",
      badgeName: "Name for badge:",
      birthDate: "Date of Birth:",
      cpf: "Tax ID (CPF):",
      passport: "Passport (foreigners):",
      nationality: "Nationality:",
      gender: "Gender:",
      marital: "Marital Status:",
      contact: "2. Contact Information",
      phone: "Phone/WhatsApp:",
      email: "E-mail:",
      address: "Address:",
      city: "City:",
      state: "State:",
      country: "Country:",
      postal: "Postal Code:",
      affiliation: "3. Ecclesiastical / Academic Affiliation",
      role: "Role/Position:",
      field: "Field of Study/Work:",
      other: "Other (Specify):",
      participation: "4. Participation Category",
      academic: "5. Academic Paper Submission",
      paperQuestion: "Will you present an academic paper?",
      paperTitle: "Paper Title:",
      thematicArea: "Thematic Area:",
      needs: "6. Special Needs",
      hasNeeds: "Do you have any specific needs?",
      which: "Specify:",
      requires: "Requirements:",
      lodging: "7. Accommodation and Logistics",
      lodgingQuestion: "Do you need information regarding accommodation?",
      arrival: "Expected arrival date:",
      departure: "Expected departure date:",
      cultural: "Will you participate in cultural events and guided tours?",
      language: "8. Preferred language",
      certification: "9. Certification",
      wantsCertificate: "Do you want a certificate?",
      certificateName: "Name exactly as it should appear on the certificate:",
      image: "10. Image use authorization",
      imageText:
        "I authorize the use of my image, voice, and participation in photographs, recordings, and broadcasts made during the 1st International Congress on the Fatherhood of God for institutional, academic, evangelistic, and promotional purposes, at no cost to the organization.",
      commitment: "11. Statement of commitment",
      commitmentText: "I declare that the information provided is true and that I am aware of the Congress participation rules.",
      commitmentCity: "City:",
      commitmentDate: "Date:",
      signature: "Signature:",
      termsAcceptancePrefix: "I have read and accept the",
      termsAcceptanceLink: "Terms of Use",
      termsAcceptanceSuffix: " to continue registration.",
      termsAcceptanceError: "Accept the Terms of Use to continue."
    },
    yesNo: ["Yes", "No"],
    sexoOptions: ["Male", "Female"],
    estadoCivilOptions: ["Single", "Married", "Religious", "Priest", "Bishop", "Other"],
    cargoOptions: ["Bishop", "Priest", "Deacon", "Religious", "Seminarian", "Layperson", "Professor", "Researcher", "Student", "Other"],
    areaAtuacaoOptions: ["Systematic Theology", "Biblical Theology", "Moral Theology", "Spirituality", "Liturgy", "Catechesis", "Pastoral Ministry", "Canon Law", "Philosophy", "Religious Studies"],
    modalidadeParticipacaoOptions: ["Participant", "Participant with certificate", "Academic Paper Presentation", "Invited Speaker"],
    specialNeedsOptions: ["Physical accessibility", "Sign Language Interpreter (Libras)", "Simultaneous translation", "Special dietary needs", "Other"],
    preferredLanguageOptions: ["Portuguese", "Spanish", "English", "Italian", "French"]
  },
  it: {
    languageLabels: { en: "Inglese", pt: "Portoghese", it: "Italiano" },
    required: "Obbligatorio",
    submitting: "Invio...",
    submit: "Iscrizione",
    remove: "Rimuovere",
    fileButton: "Allega file PDF",
    hero: [
      "1° Congresso Internazionale di Teologia",
      "Sulla paternità di Dio",
      "Tra dogma e devozione",
      "Infatti avete ricevuto uno spirito di adozione, mediante il quale gridiamo: Abbà, Padre!",
      "(Gal 4,6)"
    ],
    fields: {
      personal: "1. Dati personali",
      fullName: "Nome e cognome:",
      badgeName: "Nome per i documenti:",
      birthDate: "Data di nascita:",
      cpf: "Codice fiscale brasiliano (CPF):",
      passport: "Passaporto (per stranieri):",
      nationality: "Nazionalità:",
      gender: "Sesso:",
      marital: "Stato civile:",
      contact: "2. Informazioni di contatto",
      phone: "Telefono/WhatsApp:",
      email: "Email:",
      address: "Indirizzo:",
      city: "Città:",
      state: "Stato:",
      country: "Paese:",
      postal: "CAP:",
      affiliation: "3. Affiliazione ecclesiastica / accademica",
      role: "Posizione/Funzione:",
      field: "Area di competenza:",
      other: "Altro?",
      participation: "4. Modalità di partecipazione",
      academic: "5. Invio di un articolo accademico",
      paperQuestion: "Presenterai un lavoro accademico?",
      paperTitle: "Titolo dell'articolo:",
      thematicArea: "Area tematica:",
      needs: "6. Esigenze particolari",
      hasNeeds: "Ha esigenze particolari?",
      which: "Quali?",
      requires: "Necessità:",
      lodging: "7. Alloggio e logistica",
      lodgingQuestion: "Desidera informazioni sull'alloggio?",
      arrival: "Data di arrivo prevista:",
      departure: "Data di partenza prevista:",
      cultural: "Parteciperà agli eventi culturali e alle visite guidate?",
      language: "8. Lingua preferita",
      certification: "9. Attestato",
      wantsCertificate: "Desidera un attestato?",
      certificateName: "Nome esattamente come deve apparire sull'attestato:",
      image: "10. Autorizzazione all'utilizzo dell'immagine",
      imageText:
        "Autorizzo l'utilizzo della mia immagine, della mia voce e la mia partecipazione a fotografie, registrazioni e trasmissioni effettuate durante il 1° Congresso Internazionale di Teologia sulla Paternità di Dio, per scopi istituzionali, accademici, evangelistici e promozionali, senza alcun costo per l'organizzazione.",
      commitment: "11. Dichiarazione di impegno",
      commitmentText: "Dichiaro che le informazioni fornite sono veritiere e di essere a conoscenza del regolamento di partecipazione al Congresso.",
      commitmentCity: "Città:",
      commitmentDate: "Data:",
      signature: "Firma:",
      termsAcceptancePrefix: "Ho letto e accetto i",
      termsAcceptanceLink: "Termini di utilizzo",
      termsAcceptanceSuffix: " per continuare l'iscrizione.",
      termsAcceptanceError: "Accetta i Termini di utilizzo per continuare."
    },
    yesNo: ["Sì", "No"],
    sexoOptions: ["Maschio", "Femmina"],
    estadoCivilOptions: ["Celibe/Nubile", "Coniugato/a", "Religioso/a", "Sacerdote", "Vescovo", "Altro"],
    cargoOptions: ["Vescovo", "Sacerdote", "Diacono", "Religioso", "Seminarista", "Laico", "Professore", "Ricercatore", "Studente", "Altro"],
    areaAtuacaoOptions: ["Teologia sistematica", "Teologia biblica", "Teologia morale", "Spiritualità", "Liturgia", "Catechesi", "Pastorale", "Diritto canonico", "Filosofia", "Studi religiosi"],
    modalidadeParticipacaoOptions: ["Partecipante", "Partecipante con attestato", "Presentazione di comunicazione scientifica", "Relatore invitato"],
    specialNeedsOptions: ["Accessibilità fisica", "Interprete di lingua dei segni", "Traduzione simultanea", "Pasti speciali", "Altro"],
    preferredLanguageOptions: ["Portoghese", "Spagnolo", "Inglese", "Italiano", "Francese"]
  }
};

